# Generated by Django 5.1.5 on 2025-01-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoaccess',
            name='access_count',
            field=models.IntegerField(default=2),
        ),
    ]
