# Generated by Django 5.1.5 on 2025-01-28 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_uservideoaccess_access_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoaccess',
            name='access_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name='uservideoaccess',
            unique_together={('user', 'video')},
        ),
    ]
