# Generated by Django 5.1.5 on 2025-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title_alter_video_title_user_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideoaccess',
            name='playtime_left',
            field=models.PositiveIntegerField(default=10, help_text='User-specific playtime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='playtime',
            field=models.PositiveIntegerField(default=7, help_text='Duration in minutes'),
            preserve_default=False,
        ),
    ]
