# Generated by Django 5.1.5 on 2025-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_uservideoaccess_playtime_left_video_playtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='s3_file_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
